In [2]:
import numpy as np

arr = np.array([12.23, 13.32, 100, 36.32], ndmin=1)

print(arr)
print(arr.ndim)

[ 12.23  13.32 100.    36.32]


2. create a 3x3 matrix with values ranging from 2 to 10.

In [6]:
import numpy as np

ele = np.arange(2, 11)
arr = np.array(ele).reshape(3, 3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. create a null vector of size 10 and update 6th value to 11.

In [8]:
import numpy as np

arr = np.zeros(10)
print(arr)
arr[6] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. reverse an array(first element becomes last)

In [2]:
import numpy as np

arr = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])
res = np.flip(arr)
print(res)

[25 24 23 22 21 20 19 18 17 16 15 14 13 12]


5. create a 2D array with 1 on the border and 0 inside

In [3]:
import numpy as np

In [8]:
import numpy as np

arr = np.zeros(25).reshape(5, 5)
arr[0, :] = 1  #first row
arr[-1, :] = 1  #last row
arr[:, 0] = 1  #first col
arr[:, -1] = 1  #last col
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array

In [9]:
import numpy as np

arr = np.ones(25).reshape(5, 5)
arr[0, :] = 0
arr[-1, :] = 0
arr[:, 0] = 0
arr[:, -1] = 0
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
import numpy as np

arr = np.zeros(64).reshape(8, 8)
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays

In [19]:
import numpy as np

'''
Write a Python program to convert a list and tuple into arrays
'''
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(my_list)
print(arr)

my_tuple = ((1, 2, 3, 4, 5), (6, 7, 8, 9, 10))
arr = np.array(my_tuple)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


9. Write a Python program to append values to the end of an array

In [21]:
import numpy as np

arr = np.array([10, 20, 30])
new_arr = np.append(arr, [40, 50, 60, 70, 80, 90])
print(new_arr)

[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.

In [22]:
import numpy as np

arr = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])
print(f"Real part of array:{np.real(arr)}")
print(f"Imaginary part of array:{np.imag(arr)}")


Real part of array:[1.         0.70710678]
Imaginary part of array:[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(f"Size of the array:{len(arr)}")
print(f"Length of the array element in bytes: {arr.itemsize}")
print(f"Total bytes consumed by elements of the array: {arr.nbytes}")


Size of the array:6
Length of the array element in bytes: 8
Total bytes consumed by elements of the array: 48


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [24]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])
print(np.intersect1d(arr1, arr2))

[10 40]
