In [2]:
import numpy as np

arr = np.array([12.23,13.32,100,36.32], ndmin=1)

print(arr)
print(arr.ndim)

[ 12.23  13.32 100.    36.32]


2. create a 3x3 matrix with values ranging from 2 to 10.

In [6]:
import numpy as np
ele=np.arange(2,11)
arr=np.array(ele).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. create a null vector of size 10 and update 6th value to 11.

In [8]:
import numpy as np
arr=np.zeros(10)
print(arr)
arr[6]=11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
