Set 1 (Retail Analytics)
NumPy (Intermediate)
 A retail company records daily sales of 5 products across 30 days in a 2D NumPy array of shape (30, 5).
 Due to a system error, negative values appear in the dataset.
Task:
Replace negative values with 0

Compute the average weekly sales per product (assume 7 days = 1 week)

Identify the product with the highest average weekly sales


In [2]:
import numpy as np
from faker import Faker

fake = Faker()

sales_data=np.array([
    [fake.random_int(-5,500) for _ in range(5)]
    for _ in range(30)])
sales_data[sales_data <0]=0

weekly_sales=sales_data[:28].reshape(4,7,5)
weekly_avg=weekly_sales.mean(axis=1)

print(weekly_avg)

overall_avg=weekly_sales.mean(axis=0)
best_product=np.argmax(overall_avg)

print("Average weekly sales per product:", overall_avg)
print("Best performing product index:", best_product)


[[235.71428571 349.57142857 215.71428571 243.57142857 251.28571429]
 [255.14285714 177.         237.42857143 221.14285714 256.85714286]
 [196.28571429 282.         290.28571429 275.28571429 189.        ]
 [229.85714286 247.85714286 289.57142857 240.28571429 346.57142857]]
Average weekly sales per product: [[193.75 357.5  350.5  193.25 264.5 ]
 [158.5  351.   318.75 347.25 280.75]
 [212.5  308.5  267.5  287.5  308.25]
 [214.5  234.75 149.   232.75 163.75]
 [283.   263.   262.25 122.75 231.5 ]
 [234.5  199.   193.   284.   188.5 ]
 [308.   135.   266.75 248.   389.25]]
Best performing product index: 34
